version: "3"
services:

  web:
    container_name: web
    build:
      context: ./
      dockerfile: ./web/Dockerfile

  client:
    container_name: client
    build:
      context: ./
      dockerfile: ./client/Dockerfile
