version: "3"
services:

  web:
    container_name: web
    build:
      context: ./
      dockerfile: ./web/Dockerfile
      args: 
        TEST: this is a test argument, should show up during build...

  client:
    container_name: client
    build:
      context: ./
      dockerfile: ./client/Dockerfile
