---
name: "pre-release"

on:
  push:
    branches:
      - "master"
    tags-ignore:
      - "*"

jobs:
  gh_pre_release:
    runs-on: "ubuntu-latest"
    env:
      JEST_VERBOSE: ${{ secrets.JEST_VERBOSE }}

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2.3.4"

      - run: "python3 -m pip install pipenv"
      - run: "python3 -m pipenv install --dev"
      - run: "pipenv run pyinstaller --onefile ./FGfGwK.py"

      - uses: "./packages/automatic-releases/"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            dist/FGfGwK.exe
            options.jsonc
        id: "automatic_releases"
